name: Complete DevOps Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    # REQUIRED so GitHub Actions can commit & push changes
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t brinesh/complete-devops-project:${{ env.SHORT_SHA }} .

      - name: Login to Dockerhub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push to Dockerhub
        run: |
          docker push brinesh/complete-devops-project:${{ env.SHORT_SHA }}